version: '3.1'
services:
  api:
    container_name: quizzing-api
    build: ./api
    ports:
      - "${API_PORT}:3000"
    depends_on:
      - db

  db:
    container_name: quizzing-db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=Quizzing
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=api
      - MYSQL_PASSWORD=${DB_API_PASSWORD}
    ports:
      - "${DB_PORT}:3306"